# Generated by Django 5.2.6 on 2025-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(default='#FFFFFF', max_length=7)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ult_atualizacao', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
