# Generated by Django 5.2.6 on 2025-09-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('motoristas', '0001_initial'),
        ('produtos', '0001_initial'),
        ('situacoes', '0001_initial'),
        ('tiposcargas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_carregado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observacoes', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('assinatura_base64', models.TextField(blank=True, default='', null=True)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ult_atualizacao', models.DateTimeField(auto_now=True, db_index=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='clientes.cliente')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='motoristas.motorista')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produto')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='situacoes.situacao')),
                ('tipo_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='tiposcargas.tipocarga')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='veiculos.veiculo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
