# Generated by Django 5.2.6 on 2025-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, db_index=True, default='', max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ult_atualizacao', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
